const CATEGORIES = [
  "Electronics & Gadgets",
  "Food & Beverages",
  "Home Services",
  "Fashion & Clothing",
  "Health & Beauty",
  "Education & Training",
  "Repair & Maintenance",
  "IT & Technology",
  "Healthcare & Medical",
  "Transportation & Logistics",
  "Construction & Real Estate",
  "Financial Services",
  "Events & Entertainment",
  "Marketing & Advertising",
  "Cleaning Services",
  "Security Services",
  "Legal Services",
  "Photography & Media",
  "Sports & Fitness",
  "Automotive",
  "Pet Services",
  "Rental Services",
  "Agriculture",
  "Childcare & Senior Care",
  "Other",
];

export default CATEGORIES;
